[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ccxt>=4.5.20",
    "pandas>=2.3.3",
    "polars>=1.35.2",
    "tqdm>=4.67.1",
]
