[package]
name = "ephemera-strategy"
version = "0.1.0"
edition = "2024"

[dependencies]
ephemera-shared = { path = "../ephemera-shared" }
rust_decimal = "1.3"
tokio = { version = "1", features = ["full"] }
thiserror = "2.0"
serde = { version = "1.0.228", features = ["derive"] }
