[package]
name = "ephemera-strategy"
version = "0.1.0"
edition = "2024"

[dependencies]
ephemera-data = { path = "../ephemera-data" }
rust_decimal = "1.3"
tokio = { version = "1", features = ["full"] }
thiserror = "2.0"
