[package]
name = "ephemera-strategy"
version = "0.1.0"
edition = "2024"

[dependencies]
ephemera-shared = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

thiserror = "2.0"
serde = { version = "1.0.228", features = ["derive"] }
